---
- name: Run a play using the collections keyword
  hosts: all
  collections:
    - kubevirt.core.kubevirt_vmi_info
  tasks:
    name: Get a list of all VirtualMachinesInstances
      namespace: default
    register: vmi_list